### ISSUE TITLE
Add instructions on how to use this

### ISSUE THREAD

**Issue by ilkkapeltola** [mighty-digital/tap-apple-search-ads#2]
I'd love to use this tap, but unfortunately I cannot get it to work.

Could you add the steps required to get this to work in the readme?

I've cloned this. Ran python setup.py install in a python virtual environment. I believe I have the right config.json file but still, no cigar.

I end up with a JSON error running 
`tap-apple-search-ads -c .\config.json --catalog .\catalog.json -d`

**Comment by yehorb** [comment]
Looks like the `setup.cfg` had some errors, `*.json` files were not installed properly. I also updated the README.md with detailed installation and usage instructions, please take a look. I hope new instructions will help you to resolve your issues.

**Comment by ilkkapeltola** [comment]
This is SO helpful of you, thank you!
